version: '3'
services:
  web:
    build: ./frontend/
    ports:
    - "8093:80"
    environment:
    - API_ADDRESS=api
    links:
     - api:api
  api:
    build: quick_backend/
    environment:
    - DATABASE_URL=postgres://qdb:qdbdev@db:5432/qdb
    links:
    - db:db
    restart: on-failure
  migrations:
    build: db_migrations/
    environment:
    - DATABASE_URL=postgres://qdb:qdbdev@db:5432/qdb
    links:
    - db:db
    restart: on-failure
  db:
    image: "postgres"
    environment:
    - POSTGRES_USER=qdb
    - POSTGRES_PASSWORD=qdbdev
